
export const PRODUCT_LIST_REQUIST = "PRODUCT_LIST_REQUIST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_DETAIL_REQUIST = "PRODUCT_DETAIL_REQUIST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"


export const CARTITEM_SUCCESS = "CARTITEM_SUCCESS"
// export const CARTITEM_FAIL = "CARTITEM_FAIL"

export const CARTITEM_DELETE = "CARTITEM_DELETE"


export const USER_SIGNIN_REQUIST = "USER_SIGNIN_REQUIST"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL"

export const USER_SIGNOUT = "USER_SIGNOUT"

export const USER_REGISTER_REQUIST = "USER_REGISTER_REQUIST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"


export const USER_SHIPPING_ADDRESS = "USER_SHIPPING_ADDRESS"
